name: Run

on:
  workflow_run:
    workflows: [Close]
    types: [completed]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
